### ISSUE TITLE
Cannot use constants as enum values

### ISSUE THREAD

**Issue by OpenByteDev** [illicitonion/num_enum#94]
Since the update from 0.4.3 to 0.5.0 using a constants as the value of an enum variant does not work anymore:

```rust
const CONST_ONE: u32 = 1;
#[derive(
    TryFromPrimitive, IntoPrimitive
)]
#[repr(u32)]
pub enum Enum {
    One = CONST_ONE,
}
```

Produces the following error:
```
error: Expected literal
  --> src\error.rs:58:11
   |
58 |     One = CONST_ONE,
   |           ^^^^^^^^^
```

**Comment by kevinaboos** [comment]
Confirmed, we're facing [the same issue in Theseus OS](https://github.com/theseus-os/Theseus/pull/786/checks). Previously we were on 0.5.7, and some of our CI passes randomly started failing within the last 2 hours due to num_enum `0.5.8` breaking this. (Ultimately our mistake for not freezing/locking the lockfile versions used for doc builds)

I think 0.5.8 likely needs to be yanked.

**Comment by kevinaboos** [comment]
This is likely the culprit: https://github.com/illicitonion/num_enum/blob/4cd978d09fc4b22c5d49bef16cb9eca6bcbbbfb6/num_enum_derive/src/lib.rs#L41

**Comment by AlexDBlack** [comment]
[rdkafka](https://github.com/fede1024/rust-rdkafka) also appears to be affected:
https://github.com/fede1024/rust-rdkafka/blob/master/rdkafka-sys/src/bindings.rs#L182

```
error: Expected literal
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/rdkafka-sys-4.3.0+1.9.2/src/bindings.rs:182:32
    |
182 |     RD_KAFKA_RESP_ERR__BEGIN = -200,
    |                                ^^^^
error[E0277]: the trait bound `rd_kafka_resp_err_t: From<i32>` is not satisfied
```

We have CI builds failing just now with num_enum 0.5.8 that previously passed with 0.5.7.

**Comment by Dhghomon** [comment]
Yes, looks like this was the change that did it! I also started with a cryptic error in rdkafka which hasn't seen any changes for quite some time and eventually noticed the derive trait their error enum uses which led me to here.

Love the macro name there 😂

**Comment by illicitonion** [comment]
I've yanked 0.5.8 - thanks for the reports, and sorry for the breakage!
